### ISSUE TITLE
plot row annonation 

### ISSUE THREAD

**Issue by mimisikai** [borishejblum/TcGSA#11]
Dear Boris,

I'm using your demo data with input gmt GSA to familiarize your tool. When I input the KEGG data as 
gmt_kegg = GSA.read.gmt("....../c2.cp.kegg.v6.0.entrez.gmt") and run the script as

tcgsa_sim_1grp <- TcGSA.LR(expr=expr_1grp, gmt=gmt_kegg, design=design, 
                           subject_name="Patient_ID", time_name="TimePoint",
                           time_func="linear", crossedRandom=FALSE)

Fortunately, 15 sets matched. However, when I plot the result, the row name (should be KEGG pathway name), shown as NA:NA KEGG pathway name/NA. I wonder how to remove the NA from the annotation.  Thank you. 

Jue

**Comment by borishejblum** [comment]
Hi Jue,

First, thank you very much for your interest in TcGSA ! 
Concerning your issue, it would be very helpful if you could provide an R script which could reproduce such `NA:NA` annotation in the plots. Thus I could see if the problem comes from TcGSA itself, or rather from data formatting. What do you get when you print the summary of  `tcgsa_sim_1grp` ?

Thanks,
Boris
