### ISSUE TITLE
using TcGSA for nanostring data

### ISSUE THREAD

**Issue by ShuyiGan** [borishejblum/TcGSA#15]
Hi Boris! Hopefully I can still catch you here. I recently tried to download your TcGSA package to analyse a clinical trial dataset (nanostring of approximately 550 genes). I am just trying it out with 1 patient with 5 time points first but I keep getting an error 

Error in TcGSA::TcGSA.LR(expr = Cohort3_RawCounts, gmt = Reactome.gmt,  : 
  'expr' is not numeric. Don't know how to deal with nnon-numerical expressions.

I'm pretty new to R and wonder if this is a formatting problem but I can't fix it. All the data in the expr file is already numeric. Is there something that I'm missing?

thanks!
[Cohort3_RawCounts.txt](https://github.com/borishejblum/TcGSA/files/2231435/Cohort3_RawCounts.txt)
[DataMatrix.txt](https://github.com/borishejblum/TcGSA/files/2231436/DataMatrix.txt)
[Reactome.gmt.txt](https://github.com/borishejblum/TcGSA/files/2231437/Reactome.gmt.txt)

**Comment by borishejblum** [comment]
Hi Shuyi Gan,

First, thank you for your interest in our software.

Your error comes from the first column of Cohort3_RawCounts which is not a numeric value (`genenames`). This information should appear as `row.names` and not as a column in `expr`.

However, **I do not think that `TcGSA` is suitable for your analysis** because:
  1. you have _nanostring data_, which are count data, while `TcGSA` was developped for continuous _microarray_ data
  2. You only observe 1 patient, while `TcGSA` models the heterogeneity between patients and therefore will not be able to properly estimate the associated random effects in your case.

For those reasons, I advise not to use `TcGSA` in your case.

Best,
Boris
