### ISSUE TITLE
Convergence Messages in TCGSA and P Values in signifLRT.TcGSA

### ISSUE THREAD

**Issue by jcfoo** [borishejblum/TcGSA#17]
Dear Boris,
 
I hope that this message finds you well.  I am a researcher who is trying to use your package TcGSA to analyse some longitudinal gene expression data.  I have a couple questions which I am hoping that you can help me answer.
 
I have a dataset, which when I run using the TcGSA function and for example, the REACTOME genesets (674 gene sets), gives me warnings such as:
 
Warning messages:
1: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge with max|grad| = 0.0021925 (tol = 0.002, component 1)
2: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge with max|grad| = 0.00661041 (tol = 0.002, component 1)
3: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge with max|grad| = 0.00921315 (tol = 0.002, component 1)
4: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge with max|grad| = 0.0030303 (tol = 0.002, component 1)
5: In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge with max|grad| = 0.00666161 (tol = 0.002, component 1)
 
Do these warnings mean that for 5 of the gene sets, the models do not converge, and if so, is there any way to find out which ones?  Or does it mean that the analysis as a whole is not valid?
 
Next, in this and other analyses, when I look at the results of a run of TCGSA using the signifLRT.TcGSA command, the p value shown  for some of the significant gene sets  is 0. I would usually interpret that as it is really significant, but it seems strange that there would be no scientific notation unless it is so significant that it is not able to display.  Could you clarify about this
?
 
Thank you in advance for your help!

**Comment by borishejblum** [comment]
Dear Jerome,

Thank you for your interest in our work and in `TcGSA`.

1. In your case, `TcGSA` is estimating 2 x 674 mixed effects linear models (one under H0 and one under H1 for each gene set). It is expected that a few of them might run into numerical issues. To find out which models encountered convergence issues, you can look at the following results form the `TcGSA.LR` function:
`tcgsa_res$fit$CVG_H0`
`tcgsa_res$fit$CVG_H1`
Those vectors contains an integer for each estimated model indicating , and `0` indicates good convergence. Any other integers means that was some sort of convergence issue (you can have a look at the `lme4`package for information on what those integers mean). So by finding the index for which either `fit$CVG_H1` or `fit$CVG_H0` is not `0`, you will know for which gene set the models did not converge (NB: the models under H1 are more likely to encounter convergence issues due to higher complexity).

2. Indeed, p-values are never exactly 0, and this is an artifact of limited numerical precision. It does indicate a very significant result. 
I just pushed an update of the package on GitHub that should slightly improve the precision of computed p-values.

Best,
Boris

**Comment by jcfoo** [comment]
Dear Boris,

Thank you for your response.  I found that this method worked with the reactome set. I have more recently tried to look further into a dataset with the method that you described above in a collection of 49 gene sets. I get the error message:

Warning message:
In checkConv(attr(opt, "derivs"), opt$par, ctrl = control$checkConv,  :
  Model failed to converge with max|grad| = 0.00761705 (tol = 0.002, component 1)

But when I check further on the fit and convergences of H0 and H1, they all show zeroes, so I am unable to identify for which gene set the analysis has not converged.  Could you provide any further insight on this?

Thank you in advance,

Jerome

**Comment by borishejblum** [comment]
Dear Jerome,

I am glad you found TcGSA useful !

For more insights on convergence, I recommend reading the help page from the `lme4` package :
```{r}
?lme4::convergence
```
The warning message you are getting is likely from the `lme4::checkConv()` function, however the `lme4::lmer()` (called by TcGSA) might have some way of internally dealing with it since it does not get passed further down in the `optinfo` `S4` attribute of the fitted model (which is the code actually reported in `fit$CVG_H1` and `fit$CVG_H0`).

It's hard to be more specific without a reproducible example...

Best,
Boris

**Comment by jcfoo** [comment]
Dear Boris,

Thank you for the quick response.  I had a quick look in the documentation but wasn't really able to find anything that I could immediately use. 

I would send you the dataset to look at but it is data that I can't send out due to data protection... one work around that I will try is to split the gene set collection into parts and run TcGSA- as it is only 49 gene sets it should be relatively quick to find which one it is that doesn't converge. Since it doesn't show up in the fitness reports, it could be something else- I will update you if I find anything.

Best,

Jerome
