### ISSUE TITLE
Time course code issue

### ISSUE THREAD

**Issue by saraa30** [borishejblum/TcGSA#20]
Hello to everyone!

I am analyzing some RNA seq data in order to learn this technique. I want to make a time course with this data, and I have a problem.
After introducing this code:

tcgsa_result <- TcGSA::TcGSA.LR(expr = expr_jf,
gmt = gmt_jf,
design = design_jf,
subject_name = "Patient_ID",
time_name = "TimePoint", time_func="linear", crossedRandom=FALSE)

This error appears:

1/0 gene sets analyzed

Error in estim_expr[[gs]] <- NA :
attempt to select less than one element in integerOneIndex
Además: Warning message:
In TcGSA::TcGSA.LR(expr = expr_jf, gmt = gmt_jf, design = design_jf, :
The size of the gene set is problematic (too many or too few genes)

I have tried to solve it by using your TcGSA guide, but I am uncapable.
Thanks a lot for your time.
Regards,
Sara.

**Comment by borishejblum** [comment]
Hi Sara,

Thanks for your interest in our work.

1. TcGSA fits a mixed-effect linear model to longitudinal gene expression and has been developped to analyze microarray measurement. Thus it is not particularly well suited for RNA-seq data.

2. Your error is likely due to the format of gmt_jf not being the right one. Have a look at the documentation ragrding the GMT format.

Best,
Boris
